# Development profile — MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/rentwheels
spring.datasource.username=root
spring.datasource.password=rachi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate — auto-create/update tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
